sonar.projectKey=Davidcardig_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD-front
sonar.organization=davidcardig
sonar.projectName=BobApp - Frontend
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/coverage/**
sonar.typescript.tsconfigPath=tsconfig.json
